[package]
name = "my_project"
version = "0.1.0"
edition = "2027"

[dependencies]
crossterm = "0.26" 
rand = "0.8"
aes-gcm = "0.10"
aes = "0.8"
sha2 = "0.10"   
hkdf = "0.12"   
rand_core = "0.6"
hex = "0.4"
pbkdf2 = "0.10"
hmac = "0.12.1"
anyhow = "1.0"
